name: pytest-macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-macOS:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6-dev, 3.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest numpy
        pip install -e .
      env:
        PYTHONPATH: $PWD
    - name: Run examples
      run: |
        python examples/use_classic.py
        python examples/use_modernised.py
    - name: Test with pytest
      run: py.test -vs tests
