name: pytest-linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        python-version: [3.8, 3.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest numpy
        pip install -e .[compression]
      env:
        PYTHONPATH: $PWD
    - name: Run examples
      run: |
        python examples/use_classic.py
        python examples/use_modernised.py
    - name: Test with pytest
      run: py.test -vs tests

