name: pytest-linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-linux:
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-9

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        python-version: [3.10, 3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade importlib_metadata pytest numpy
        python3 -m pip install -e .[compression]
      env:
        PYTHONPATH: $PWD

    - name: Run examples
      run: |
        python3 examples/use_classic.py
        python3 examples/use_modernised.py

    - name: Test with pytest
      run: py.test -vs tests

